### PR TITLE
Elytra and cape animation support.

### PR DESCRIPTION
**Pull request by ZigyTheBird**
Not tested, I mean, the port isn't even done yet.
I also saw that the cape bug fixes didn't make it to this version so here they are.
Related Emotecraft PR: https://github.com/KosmX/emotes/pull/512
I will back port this to 1.21 and test it when I have the energy.

### CODE REVIEW

**Comment by ZigyTheBird** [comment]
Actually not sure about that back porting part, maybe 1.21.3 should become the main branch then we can back port everything if there is demand for it.

**Comment by KosmX** [comment]
oops, I just broke this... sorry

**Comment by ZigyTheBird** [comment]
moyai_wahhhh

**Comment by KosmX** [comment]
don't worry, I'm merging this

**Comment by KosmX** [comment]
thank you for allowing me to push into your repo

**Comment by KosmX** [comment]
I'll fix remaining issues in my branch, thank you

**Comment by KosmX** [comment]
Actually the `this.model instanceof CapeLayerAccessor capeLayer` wouldn't even work. It is an accessor, but the field it was accessing was removed.

**Comment by ZigyTheBird** [comment]
Sorry! gradle wouldn't reload so I was kind of coding blind

**Comment by KosmX** [comment]
No problem. I'll make this work.

**Pull request merged**
