### PR TITLE
Add scaling support

### PR DESCRIPTION
**Pull request by dima-dencep**
Adds scaling support for bones (full geckolib scale support)

https://github.com/user-attachments/assets/f30829ae-1a70-4258-ab28-cc9ff88fd4f0
https://github.com/user-attachments/assets/7a58ddca-e2fa-4049-b158-b78e4d8d1480

### CODE REVIEW

**Comment by dima-dencep** [comment]
Last bug: the scale of the hand occurs in the space of the hand itself

**Comment by dima-dencep** [comment]
I'm not sure if it's a bug though, since the hand still has one cuboid and bendylib doesn't create an extra one to make everything work properly

**Comment by ZigyTheBird** [comment]
Have you gotten this working with Blender animations?

**Comment by KosmX** [comment]
This one's nice, I'm merging it soon

**Comment by dima-dencep** [comment]
> Have you gotten this working with Blender animations?

Yes, I asked my friend to write a script for my changes, you can check it out for yourself
[scale.json](https://github.com/user-attachments/files/16494529/scale.json)

**Pull request merged**
